#!/bin/bash
set -e

echo "==================================="
echo "Bingo Laravel API - Starting..."
echo "==================================="

# Wait for MySQL to be ready
if [ -n "$DB_HOST" ]; then
    echo "Waiting for MySQL at $DB_HOST:${DB_PORT:-3306}..."
    
    for i in {1..30}; do
        if nc -z "${DB_HOST}" "${DB_PORT:-3306}" 2>/dev/null; then
            echo "MySQL is ready!"
            break
        fi
        
        if [ $i -eq 30 ]; then
            echo "❌ Error: Could not connect to MySQL after 30 attempts (60 seconds)"
            echo "   Please check if MySQL container is running and healthy."
            exit 1
        fi
        
        echo "Attempt $i/30: MySQL not ready yet, waiting..."
        sleep 2
    done
fi

# Create config directory if it doesn't exist
mkdir -p /var/www/html/config

# Generate database config from environment variables
if [ -n "$DB_HOST" ]; then
    echo "Generating database configuration from environment variables..."
    cat > /var/www/html/config/database.php << EOF
<?php
/**
 * Database configuration
 * Auto-generated by Docker entrypoint
 */

return [
    'host' => '${DB_HOST}',
    'port' => '${DB_PORT:-3306}',
    'database' => '${DB_DATABASE:-bingo}',
    'username' => '${DB_USERNAME:-bingo_user}',
    'password' => '${DB_PASSWORD:-bingo_password}',
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
];
EOF
    
    echo "Database configuration created successfully!"
fi

# Set proper permissions
chown -R www-data:www-data /var/www/html/config
chmod -R 775 /var/www/html/config

echo "==================================="
echo "Starting Apache..."
echo "==================================="

# Execute the main command
exec "$@"
