version: "3.7"

services:
  ## --------------------------- BINGO APP --------------------------- ##
  bingo_app:
    image: josemaeldon/bingo-system:app-latest
    networks:
      - luzianet
    environment:
      - VITE_API_BASE_URL=https://api.bingo.santaluzia.org
      - VITE_BASIC_AUTH_USER=
      - VITE_BASIC_AUTH_PASS=
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.bingo_app.rule=Host(`bingo.santaluzia.org`)
        - traefik.http.routers.bingo_app.entrypoints=websecure
        - traefik.http.routers.bingo_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.bingo_app.service=bingo_app
        - traefik.http.services.bingo_app.loadbalancer.server.port=80
        - traefik.http.services.bingo_app.loadbalancer.passHostHeader=true

  ## --------------------------- BINGO BACKEND --------------------------- ##
  bingo_backend:
    image: josemaeldon/bingo-system:backend-latest
    networks:
      - luzianet
    environment:
      - POSTGRES_HOST=bingo_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bingo
      - POSTGRES_USER=bingo
      - POSTGRES_PASSWORD=SuaSenhaSegura123
      - JWT_SECRET=SuaChaveJWTSuperSecreta2024
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.bingo_backend.rule=Host(`api.bingo.santaluzia.org`)
        - traefik.http.routers.bingo_backend.entrypoints=websecure
        - traefik.http.routers.bingo_backend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.bingo_backend.service=bingo_backend
        - traefik.http.services.bingo_backend.loadbalancer.server.port=3001
        - traefik.http.services.bingo_backend.loadbalancer.passHostHeader=true

  ## --------------------------- POSTGRES --------------------------- ##
  bingo_postgres:
    image: postgres:15-alpine
    networks:
      - luzianet
    environment:
      - POSTGRES_USER=bingo
      - POSTGRES_PASSWORD=SuaSenhaSegura123
      - POSTGRES_DB=bingo
    volumes:
      - bingo_postgres_data:/var/lib/postgresql/data
    configs:
      - source: bingo_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

## --------------------------- VOLUMES --------------------------- ##
volumes:
  bingo_postgres_data:
    external: true
    name: bingo_postgres_data

## --------------------------- CONFIGS --------------------------- ##
configs:
  bingo_init_sql:
    external: true
    name: bingo_init_sql

## --------------------------- NETWORKS --------------------------- ##
networks:
  luzianet:
    name: luzianet
    external: true
